### PR TITLE
Update mdah.js

### PR DESCRIPTION
**Pull request by jonferreira**
adds planID management for rooms #57 

known bugs: encoding problem on "º", no idea why :-(

### CODE REVIEW

**Comment by jonferreira** [comment]
OK looks like I was one commit behind so you can't just merge it :-(

**Comment by jonferreira** [comment]
I'm not sure if you've noticed but there's a big chunk of code missing at line 1972, I was one commit behind :(

**Comment by empierre** [comment]
Yes I did, it is now fixed !
Thanks for the brute work (changing in every device), this was the most painful part ;-)
In fact I had the written code ready but had no time to make it yet., so a BIG thanks !
Will test that further later, can't do it tonight , and will launch a release if this is ok. 
If you want to test it, just change the mdah.js in /usr/share/mydomoathome/lib

**Comment by jonferreira** [comment]
Glad I could help :-)

I've tested it already - manually changed the mdah.js on my installation - and it has been working fine so far with all my devices.

Well I still have that encoding problem, not sure why :-(

**Comment by empierre** [comment]
whi do you say known bug ? should I raise it to IH ?

**Comment by empierre** [comment]
I'll add a bit of strenghtening, it fails when there is no domoticz around, there is an idiomatic like this to add:
 (typeof data.PlanIDs !== 'undefined' && data.PlanIDs !== null) {

::ffff:127.0.0.1 - - [15/Apr/2016:12:16:10 +0000] "GET /rooms HTTP/1.1" 200 12 "-" "node-superagent/1.8.3"
  Devices
  ◦ Testing call to http://localhost:3002/devices
/home/travis/build/empierre/MyDomoAtHome/mdah.js:722
    if(data.PlanIDs[0] > 0) {
                   ^

**Comment by jonferreira** [comment]
I meant I knew that wasn't working properly for me and it's somehow my fault since it was working fine before...there's a chance it's due to the way I've saved my mdah.js file and once you compile it it will be fine.

all I can say is in /devices the "º" is all messed up - "unit":"�C"

ah yes, you're totally right, I should have done this from the start!

**Comment by empierre** [comment]
will see that, it is often encoding related (has a bad time in perl for this)

**Comment by jonferreira** [comment]
hopefully it will go smooth this time :-)

**Pull request merged**
