### PR TITLE
basic Energy Usage support

### PR DESCRIPTION
**Pull request by jonferreira**
adds basic Energy Usage support as discussed in #73 

I can confirm that it works with most devices however i've noticed some exceptions, I have no idea how to figure out the logic behind

### CODE REVIEW

**Comment by empierre** [comment]
huh will have to test your logic, from the pull it is hard to see if this is right

**Comment by jonferreira** [comment]
sorry, missed the notification.

In a nutshell I've created an Electric devices array indexed by ID and it's current Energy consumption.
On every request I check if the requested device "ID minus left zero" exists on the array and if yes I attach the Energy value to the payload

It works fine and it'0s the most efficient way I've found to do this. Problem is on domoticz side, so far I've noticed the Fibaro Original Dimmer and the Fibaro Wall Plug doesn't follow this logic but we'll need more users input to make sure

**Comment by empierre** [comment]
can't merge here, pushed on my branch instead...

**Comment by jonferreira** [comment]
still can't get it to install with apt-get

MyDomoAtHome:
  Installed: 0.1.17
  Candidate: 1.0.9
  Version table:
     1.0.9 0
        500 http://www.e-nef.com/domoticz/mdah/  Packages
     1.0.8 0
        500 http://www.e-nef.com/domoticz/mdah/  Packages
 **\* 0.1.17 0
        100 /var/lib/dpkg/status
     0.1.10 0
        500 http://www.e-nef.com/domoticz/mdah/  Packages
        500 http://www.e-nef.com/domoticz/mdah/  Packages
     0.1.7 0
        500 http://www.e-nef.com/domoticz/mdah/  Packages
     0.1.6 0
        500 http://www.e-nef.com/domoticz/mdah/  Packages
     0.1.4 0
        500 http://www.e-nef.com/domoticz/mdah/  Packages
     0.1.3 0
        500 http://www.e-nef.com/domoticz/mdah/  Packages
     0.1.2 0
        500 http://www.e-nef.com/domoticz/mdah/  Packages
     0.1.1 0
        500 http://www.e-nef.com/domoticz/mdah/  Packages
     0.1.0 0
        500 http://www.e-nef.com/domoticz/mdah/  Packages

**Comment by jonferreira** [comment]
any manual installed it and seems to be working fine, no sign of that pesky encoding issue.
great work! :-)

**Pull request closed without merging**
